# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Vega Strike
url: https://www.vega-strike.org
logo: /assets/img/shorttext-square-color-logo.png
email: nabaco@tutamail.com
description: >- # this means to ignore newlines until "baseurl:"
    Open Source 3D Space Flight Sim: Trade, Fight, Explore
lang: en_US

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.vega-strike.org" # the base hostname & protocol for your site, e.g. http://example.com
git_address: https://github.com/vegastrike/Vega-Strike-Engine-Source
git_edit_address: https://github.com/vegastrike/vegastrike.github.io/blob/master
github_username:  vegastrike
gitter: https://gitter.im/vegastrike/community
google_site_verification: z7w-3d4YMTeLVhjeVElqaV1_qmjG-zKJzKGVDgZucvY

engine_download_url: https://github.com/vegastrike/Vega-Strike-Engine-Source/releases
vsutcs_download_url: https://github.com/vegastrike/Assets-Production/releases

# theme options from https://bootswatch.com/3/
# comment out this to use default Bootstrap
bootwatch: cyborg #paper cerulean cosmo custom cyborg darkly flatly journal lumen readable sandstone simplex slate solar spacelab superhero united yeti

# Build settings
markdown: kramdown
highlighter: rouge
#theme: minima
#remote_theme: aksakalli/jekyll-doc-theme@gh-pages

# Plugins (previously gems:)
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
  - vendor/bundle/
  - vendor/cache
  - vendor/gems/
  - vendor/ruby/

defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: News

- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: Games

- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: Docs
    seo:
      type: "WebPage"

- scope:
    path: _pages
    type: pages
  values:
    layout: page

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true
  pages:
      permalink: /:path/
